version: '3.4'

networks:
  sio-proj1-webapi-dev:
    driver: bridge

services:
  sio-proj1-webapi:
    image: ${DOCKER_REGISTRY-}sioproj1webapi
    depends_on:
        - "postgres_image"
    build:
      context: .
      dockerfile: sio-proj1-webapi/Dockerfile
    ports:
        - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=sioproj1db;Username=postgres;Password=mysecretpassword"
    networks:
        - sio-proj1-webapi-dev
 

  postgres_image:
    image: postgres:latest
    ports:
        - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    networks:
      - sio-proj1-webapi-dev
